require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'bin/**'
    - 'Rakefile'
    - 'toycol.gemspec'
  NewCops: enable
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - lib/toycol/server.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  Exclude:
    - lib/toycol/server.rb

Metrics:
  Exclude:
    - lib/toycol/proxy.rb
    - lib/toycol/server.rb

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 15
